# Safe Driver prediction
In this competition, you’re challenged to build a model that predicts the probability that a driver will initiate an auto insurance claim in the next year

By James Dietle @jamesdietle

Referances:
- Who we are borrowing from Jeremy Howard's Rossman
- https://www.kaggle.com/c/porto-seguro-safe-driver-prediction

# 1. Dependencies
Things that we need to function or that are just nice
    
    - import functions 
    - correct paths and folders
    - cell noises

In [1]:
# Put these at the top of every notebook, to get automatic reloading and inline plotting
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
# Gives times for each block 
get_ipython().magic('load_ext cellevents')

# Set up paths on computer
path = '/home/jd/data/PortoDriver/'

## Import up sound alert dependencies; I really like sounds
from IPython.display import Audio, display

def allDone():
    #display(Audio(url='https://sound.peal.io/ps/audios/000/000/537/original/woo_vu_luvub_dub_dub.wav', autoplay=True))
    display(Audio(url='http://starmen.net/mother2/soundfx/eb_win.wav', autoplay=True))
    
def RunningEpochs():
    #display(Audio(url='https://sound.peal.io/ps/audios/000/000/537/original/woo_vu_luvub_dub_dub.wav', autoplay=True))
    display(Audio(url='http://starmen.net/mother2/soundfx/enterbattle.wav', autoplay=True))

In [3]:
from fastai.imports import *
from fastai.torch_imports import *
from fastai.structured import *
from fastai.dataset import *
from fastai.column_data import *
np.set_printoptions(threshold=50, edgeitems=20)

from sklearn_pandas import DataFrameMapper
from sklearn.preprocessing import LabelEncoder, Imputer, StandardScaler
import operator


time: 599 ms


# 2. Functions
Functions being run by the program

In [4]:
def inv_y(a): return np.exp(a)

def exp_rmspe(y_pred, targ):
    targ = inv_y(targ)
    pct_var = (targ - inv_y(y_pred))/targ
    return math.sqrt((pct_var**2).mean())

time: 2.3 ms


# 3. Load in data
Loads the data we are working with into the program
- Data set provided
- Other unique datasets that would help

We are training to target

In [5]:
samplesub = pd.read_csv(f'{path}sample_submission.csv', low_memory=False)
test = pd.read_csv(f'{path}test.csv', low_memory=False)
train = pd.read_csv(f'{path}train.csv', low_memory=False)

time: 7.73 s


In [6]:
# Sample size to speed everything up
size = 3000
test = test[:size]
train = train [:size]

time: 1.46 ms


In [7]:
samplesub[:5]

id  target
0   0  0.0364
1   1  0.0364
2   2  0.0364
3   3  0.0364
4   4  0.0364

time: 5.52 ms


In [8]:
test[:5].columns

Index(['id', 'ps_ind_01', 'ps_ind_02_cat', 'ps_ind_03', 'ps_ind_04_cat',
       'ps_ind_05_cat', 'ps_ind_06_bin', 'ps_ind_07_bin', 'ps_ind_08_bin',
       'ps_ind_09_bin', 'ps_ind_10_bin', 'ps_ind_11_bin', 'ps_ind_12_bin',
       'ps_ind_13_bin', 'ps_ind_14', 'ps_ind_15', 'ps_ind_16_bin',
       'ps_ind_17_bin', 'ps_ind_18_bin', 'ps_reg_01', 'ps_reg_02', 'ps_reg_03',
       'ps_car_01_cat', 'ps_car_02_cat', 'ps_car_03_cat', 'ps_car_04_cat',
       'ps_car_05_cat', 'ps_car_06_cat', 'ps_car_07_cat', 'ps_car_08_cat',
       'ps_car_09_cat', 'ps_car_10_cat', 'ps_car_11_cat', 'ps_car_11',
       'ps_car_12', 'ps_car_13', 'ps_car_14', 'ps_car_15', 'ps_calc_01',
       'ps_calc_02', 'ps_calc_03', 'ps_calc_04', 'ps_calc_05', 'ps_calc_06',
       'ps_calc_07', 'ps_calc_08', 'ps_calc_09', 'ps_calc_10', 'ps_calc_11',
       'ps_calc_12', 'ps_calc_13', 'ps_calc_14', 'ps_calc_15_bin',
       'ps_calc_16_bin', 'ps_calc_17_bin', 'ps_calc_18_bin', 'ps_calc_19_bin',
       'ps_calc_20_bin'],
      dtyp

time: 2.17 ms


# 4. Manipulate Data
Prepares the data for training, determines features
- Cuts into sets
- Determines features
- Augments data
	1. More data
	2. Data augmentation
	3. Generalize wel with architectures
	4. Add regularization
    5. Reduce architecture complexity

# 5. Prepare Model
Sets up the model
    - choose optimizer
    - choose format
    - choose loss function

In the train and test data, features that belong to similar groupings are tagged as such in the feature names (e.g., ind, reg, car, calc). In addition, feature names include the postfix bin to indicate binary features and cat to indicate categorical features. Features without these designations are either continuous or ordinal. Values of -1 indicate that the feature was missing from the observation. The target columns signifies whether or not a claim was filed for that policy holder.

Ind category
'ps_ind_01', 'ps_ind_02_cat', 'ps_ind_03',
       'ps_ind_04_cat', 'ps_ind_05_cat', 

ind binary
'ps_ind_06_bin', 'ps_ind_07_bin',
       'ps_ind_08_bin', 'ps_ind_09_bin', 'ps_ind_10_bin', 'ps_ind_11_bin',
       'ps_ind_12_bin', 'ps_ind_13_bin', 'ps_ind_14', 'ps_ind_15',
       'ps_ind_16_bin', 'ps_ind_17_bin', 'ps_ind_18_bin'
    
reg - continous     
        'ps_reg_01',
       'ps_reg_02', 'ps_reg_03', 

car category
    'ps_car_01_cat', 'ps_car_02_cat',
       'ps_car_03_cat', 'ps_car_04_cat', 'ps_car_05_cat', 'ps_car_06_cat',
       'ps_car_07_cat', 'ps_car_08_cat', 'ps_car_09_cat', 'ps_car_10_cat',
       'ps_car_11_cat', 'ps_car_11', 'ps_car_12', 'ps_car_13', 
        
car - cont
'ps_car_14',
       'ps_car_15', 'ps_calc_01', 'ps_calc_02', 'ps_calc_03', 'ps_calc_04',
       'ps_calc_05', 'ps_calc_06', 'ps_calc_07', 'ps_calc_08', 'ps_calc_09',
       'ps_calc_10', 'ps_calc_11', 'ps_calc_12', 'ps_calc_13', 'ps_calc_14',
car - cat
       'ps_calc_15_bin', 'ps_calc_16_bin', 'ps_calc_17_bin', 'ps_calc_18_bin',
       'ps_calc_19_bin', 'ps_calc_20_bin']/*

In [9]:
## Move training set over
joined = train

time: 637 µs


In [10]:
# Adding the validation set to the training set
#joined=joined.append(test)

time: 528 µs


In [11]:
## This works, but appears to break later
joined=joined.replace(-1, np.NaN)
##
#joined=joined.fillna(0)

time: 5.1 ms


In [12]:
joined.target=joined.target.replace(0, .001)

time: 1.74 ms


In [13]:
#joined= joined.set_index('id')

time: 529 µs


In [14]:
joined

id  target  ps_ind_01  ps_ind_02_cat  ps_ind_03  ps_ind_04_cat  \
0        7   0.001          2            2.0          5            1.0   
1        9   0.001          1            1.0          7            0.0   
2       13   0.001          5            4.0          9            1.0   
3       16   0.001          0            1.0          2            0.0   
4       17   0.001          0            2.0          0            1.0   
5       19   0.001          5            1.0          4            0.0   
6       20   0.001          2            1.0          3            1.0   
7       22   0.001          5            1.0          4            0.0   
8       26   0.001          5            1.0          3            1.0   
9       28   1.000          1            1.0          2            0.0   
10      34   0.001          5            2.0          2            0.0   
11      35   0.001          2            1.0          3            1.0   
12      36   0.001          2            1.0          1            1.0   
13      43   0.001          1            1.0          3            1.0   
14      46   0.001          5            1.0         11            0.0   
15      48   0.001          5            1.0          3            1.0   
16      50   0.001          1            2.0          1            0.0   
17      58   0.001          5            1.0          6            0.0   
18      61   0.001          5            1.0          8            0.0   
19      64   1.000          0            1.0          2            1.0   
20      65   0.001          0            1.0          2            0.0   
21      66   0.001          0            1.0          5            1.0   
22      72   0.001          5            3.0          6            1.0   
23      74   0.001          2            1.0          2            1.0   
24      77   0.001          0            1.0          2            0.0   
25      78   0.001          0            1.0          7            0.0   
26      79   0.001          0            1.0          4            1.0   
27      80   0.001          4            1.0          6            0.0   
28      84   1.000          0            2.0          0            1.0   
29      85   0.001          3            2.0          2            0.0   
...    ...     ...        ...            ...        ...            ...   
2970  7572   0.001          0            2.0          2            1.0   
2971  7577   0.001          1            1.0          5            0.0   
2972  7578   0.001          5            1.0          6            1.0   
2973  7580   0.001          5            1.0          2            1.0   
2974  7581   0.001          0            1.0          3            1.0   
2975  7593   0.001          1            1.0          7            1.0   
2976  7594   0.001          1            1.0          2            0.0   
2977  7596   0.001          6            2.0          9            0.0   
2978  7597   0.001          3            2.0          2            0.0   
2979  7603   0.001          0            2.0          1            0.0   
2980  7606   0.001          0            1.0          3            0.0   
2981  7607   0.001          4            1.0          2            0.0   
2982  7608   0.001          1            1.0          2            1.0   
2983  7612   0.001          0            1.0          2            0.0   
2984  7613   0.001          0            1.0          6            1.0   
2985  7614   0.001          3            2.0          2            0.0   
2986  7615   0.001          0            1.0          2            0.0   
2987  7617   0.001          5            1.0          2            0.0   
2988  7620   0.001          3            1.0          4            1.0   
2989  7621   0.001          1            1.0          6            0.0   
2990  7622   0.001          1            1.0          8            1.0   
2991  7623   0.001          4            1.0          5            0.0   
2992  7624  

time: 40.6 ms


In [15]:
joined.to_feather(f'{path}joined')

time: 20.7 ms


## Create Features

In [91]:
joined = pd.read_feather(f'{path}joined')

time: 2.41 ms


In [92]:
joined[:5]

id  target  ps_ind_01  ps_ind_02_cat  ps_ind_03  ps_ind_04_cat  \
0   7   0.001          2            2.0          5            1.0   
1   9   0.001          1            1.0          7            0.0   
2  13   0.001          5            4.0          9            1.0   
3  16   0.001          0            1.0          2            0.0   
4  17   0.001          0            2.0          0            1.0   

   ps_ind_05_cat  ps_ind_06_bin  ps_ind_07_bin  ps_ind_08_bin       ...        \
0            0.0              0              1              0       ...         
1            0.0              0              0              1       ...         
2            0.0              0              0              1       ...         
3            0.0              1              0              0       ...         
4            0.0              1              0              0       ...         

   ps_calc_11  ps_calc_12  ps_calc_13  ps_calc_14  ps_calc_15_bin  \
0           9           1           5           8               0   
1           3           1           1           9               0   
2           4           2           7           7               0   
3           2           2           4           9               0   
4           3           1           1           3               0   

   ps_calc_16_bin  ps_calc_17_bin  ps_calc_18_bin  ps_calc_19_bin  \
0               1               1               0               0   
1               1               1               0               1   
2               1               1               0               1   
3               0               0               0               0   
4               0               0               1               1   

   ps_calc_20_bin  
0               1  
1               0  
2               0  
3               0  
4               0  

[5 rows x 59 columns]

time: 14 ms


In [93]:
cat_vars = [
    #'id', 
    'ps_ind_02_cat', 
       'ps_ind_04_cat', 'ps_ind_05_cat','ps_ind_06_bin', 'ps_ind_07_bin',
       'ps_ind_08_bin', 'ps_ind_09_bin', 'ps_ind_10_bin', 'ps_ind_11_bin',
       'ps_ind_12_bin', 'ps_ind_13_bin', 
       'ps_ind_16_bin', 'ps_ind_17_bin', 'ps_ind_18_bin', 'ps_car_01_cat', 'ps_car_02_cat',
       'ps_car_03_cat', 'ps_car_04_cat', 'ps_car_05_cat', 'ps_car_06_cat',
       'ps_car_07_cat', 'ps_car_08_cat', 'ps_car_09_cat', 'ps_car_10_cat',
       'ps_car_11_cat',
        'ps_calc_15_bin', 'ps_calc_16_bin', 'ps_calc_17_bin', 'ps_calc_18_bin',
    'ps_calc_19_bin', 'ps_calc_20_bin']

contin_vars = ['ps_car_11', 'ps_car_12', 'ps_car_13','ps_ind_14', 'ps_ind_15','ps_ind_01','ps_ind_03','ps_reg_01','ps_reg_02', 'ps_reg_03', 'ps_car_14',
       'ps_car_15', 'ps_calc_01', 'ps_calc_02', 'ps_calc_03', 'ps_calc_04',
       'ps_calc_05', 'ps_calc_06', 'ps_calc_07', 'ps_calc_08', 'ps_calc_09',
       'ps_calc_10', 'ps_calc_11', 'ps_calc_12', 'ps_calc_13', 'ps_calc_14']

n = len(joined); n

3000

time: 6.2 ms


In [94]:
type(cat_vars)

list

time: 1.34 ms


In [95]:
joined[:5]

id  target  ps_ind_01  ps_ind_02_cat  ps_ind_03  ps_ind_04_cat  \
0   7   0.001          2            2.0          5            1.0   
1   9   0.001          1            1.0          7            0.0   
2  13   0.001          5            4.0          9            1.0   
3  16   0.001          0            1.0          2            0.0   
4  17   0.001          0            2.0          0            1.0   

   ps_ind_05_cat  ps_ind_06_bin  ps_ind_07_bin  ps_ind_08_bin       ...        \
0            0.0              0              1              0       ...         
1            0.0              0              0              1       ...         
2            0.0              0              0              1       ...         
3            0.0              1              0              0       ...         
4            0.0              1              0              0       ...         

   ps_calc_11  ps_calc_12  ps_calc_13  ps_calc_14  ps_calc_15_bin  \
0           9           1           5           8               0   
1           3           1           1           9               0   
2           4           2           7           7               0   
3           2           2           4           9               0   
4           3           1           1           3               0   

   ps_calc_16_bin  ps_calc_17_bin  ps_calc_18_bin  ps_calc_19_bin  \
0               1               1               0               0   
1               1               1               0               1   
2               1               1               0               1   
3               0               0               0               0   
4               0               0               1               1   

   ps_calc_20_bin  
0               1  
1               0  
2               0  
3               0  
4               0  

[5 rows x 59 columns]

time: 13.9 ms


In [96]:
samp_size = n
joined_samp = joined

time: 812 µs


In [97]:
joined

id  target  ps_ind_01  ps_ind_02_cat  ps_ind_03  ps_ind_04_cat  \
0        7   0.001          2            2.0          5            1.0   
1        9   0.001          1            1.0          7            0.0   
2       13   0.001          5            4.0          9            1.0   
3       16   0.001          0            1.0          2            0.0   
4       17   0.001          0            2.0          0            1.0   
5       19   0.001          5            1.0          4            0.0   
6       20   0.001          2            1.0          3            1.0   
7       22   0.001          5            1.0          4            0.0   
8       26   0.001          5            1.0          3            1.0   
9       28   1.000          1            1.0          2            0.0   
10      34   0.001          5            2.0          2            0.0   
11      35   0.001          2            1.0          3            1.0   
12      36   0.001          2            1.0          1            1.0   
13      43   0.001          1            1.0          3            1.0   
14      46   0.001          5            1.0         11            0.0   
15      48   0.001          5            1.0          3            1.0   
16      50   0.001          1            2.0          1            0.0   
17      58   0.001          5            1.0          6            0.0   
18      61   0.001          5            1.0          8            0.0   
19      64   1.000          0            1.0          2            1.0   
20      65   0.001          0            1.0          2            0.0   
21      66   0.001          0            1.0          5            1.0   
22      72   0.001          5            3.0          6            1.0   
23      74   0.001          2            1.0          2            1.0   
24      77   0.001          0            1.0          2            0.0   
25      78   0.001          0            1.0          7            0.0   
26      79   0.001          0            1.0          4            1.0   
27      80   0.001          4            1.0          6            0.0   
28      84   1.000          0            2.0          0            1.0   
29      85   0.001          3            2.0          2            0.0   
...    ...     ...        ...            ...        ...            ...   
2970  7572   0.001          0            2.0          2            1.0   
2971  7577   0.001          1            1.0          5            0.0   
2972  7578   0.001          5            1.0          6            1.0   
2973  7580   0.001          5            1.0          2            1.0   
2974  7581   0.001          0            1.0          3            1.0   
2975  7593   0.001          1            1.0          7            1.0   
2976  7594   0.001          1            1.0          2            0.0   
2977  7596   0.001          6            2.0          9            0.0   
2978  7597   0.001          3            2.0          2            0.0   
2979  7603   0.001          0            2.0          1            0.0   
2980  7606   0.001          0            1.0          3            0.0   
2981  7607   0.001          4            1.0          2            0.0   
2982  7608   0.001          1            1.0          2            1.0   
2983  7612   0.001          0            1.0          2            0.0   
2984  7613   0.001          0            1.0          6            1.0   
2985  7614   0.001          3            2.0          2            0.0   
2986  7615   0.001          0            1.0          2            0.0   
2987  7617   0.001          5            1.0          2            0.0   
2988  7620   0.001          3            1.0          4            1.0   
2989  7621   0.001          1            1.0          6            0.0   
2990  7622   0.001          1            1.0          8            1.0   
2991  7623   0.001          4            1.0          5            0.0   
2992  7624  

time: 39.9 ms


In [98]:
for v in cat_vars: joined[v] = joined[v].astype('category').cat.as_ordered()
for v in contin_vars: joined[v] = joined[v].astype('float32')
dep = 'target'
#joined = joined[cat_vars+contin_vars+[dep,'id']]
joined = joined[cat_vars+contin_vars+[dep]]

time: 27.2 ms


In [99]:
joined_samp = joined.set_index('id')
#??joined.set_index

KeyError: 'id'

time: 33.4 ms


In [100]:
df, y, nas, mapper = proc_df(joined_samp, 'target', do_scale=True)
yl = y
yl

array([ 0.001,  0.001,  0.001,  0.001,  0.001,  0.001,  0.001,  0.001,  0.001,  1.   ,  0.001,  0.001,  0.001,
        0.001,  0.001,  0.001,  0.001,  0.001,  0.001,  1.   , ...,  0.001,  0.001,  0.001,  0.001,  0.001,
        0.001,  0.001,  0.001,  0.001,  0.001,  0.001,  0.001,  0.001,  0.001,  0.001,  0.001,  0.001,  0.001,
        0.001,  0.001])

time: 62.1 ms


In [101]:
df[:5]

id  ps_ind_01  ps_ind_02_cat  ps_ind_03  ps_ind_04_cat  \
0 -1.745605   0.073402              2   0.235139              2   
1 -1.744698  -0.443513              1   0.983196              1   
2 -1.742883   1.624146              4   1.731252              2   
3 -1.741522  -0.960428              1  -0.886945              1   
4 -1.741068  -0.960428              2  -1.635002              2   

   ps_ind_05_cat  ps_ind_06_bin  ps_ind_07_bin  ps_ind_08_bin  ps_ind_09_bin  \
0              1              1              2              1              1   
1              1              1              1              2              1   
2              1              1              1              2              1   
3              1              2              1              1              1   
4              1              2              1              1              1   

       ...       ps_calc_13  ps_calc_14  ps_calc_15_bin  ps_calc_16_bin  \
0      ...         1.278082    0.148102               1               2   
1      ...        -1.112718    0.505549               1               2   
2      ...         2.473482   -0.209345               1               2   
3      ...         0.680382    0.505549               1               1   
4      ...        -1.112718   -1.639133               1               1   

   ps_calc_17_bin  ps_calc_18_bin  ps_calc_19_bin  ps_calc_20_bin  \
0               2               1               1               2   
1               2               1               2               1   
2               2               1               2               1   
3               1               1               1               1   
4               1               2               2               1   

   ps_reg_03_na  ps_car_14_na  
0     -0.467992     -0.267976  
1     -0.467992     -0.267976  
2      2.136788     -0.267976  
3     -0.467992     -0.267976  
4     -0.467992     -0.267976  

[5 rows x 60 columns]

time: 13.9 ms


In [102]:
y[:5]

array([ 0.001,  0.001,  0.001,  0.001,  0.001])

time: 1.8 ms


In [103]:
nas

{'ps_car_14': 0.37349697947502136, 'ps_reg_03': 0.7933315634727478}

time: 1.49 ms


In [104]:
mapper

DataFrameMapper(default=False, df_out=False,
        features=[(['id'], StandardScaler(copy=True, with_mean=True, with_std=True)), (['ps_ind_01'], StandardScaler(copy=True, with_mean=True, with_std=True)), (['ps_ind_03'], StandardScaler(copy=True, with_mean=True, with_std=True)), (['ps_ind_14'], StandardScaler(copy=True, with_mean=True, with_std=True)...True, with_std=True)), (['ps_car_14_na'], StandardScaler(copy=True, with_mean=True, with_std=True))],
        input_df=False, sparse=False)

time: 2.89 ms


In [105]:
len(joined)

3000

time: 1.44 ms


In [106]:
joined.target[2995:3005]

2995    0.001
2996    0.001
2997    0.001
2998    0.001
2999    0.001
Name: target, dtype: float64

time: 2.35 ms


In [107]:
df.index[50]

50

time: 1.58 ms


In [110]:
val_idx = list(range(2500, 2999))
val_idx = np.array(val_idx)
#flatnonzero((df.index<=7578) & (df.index>=10000))

time: 1.17 ms


In [111]:
type(val_idx), val_idx

(numpy.ndarray,
 array([2500, 2501, 2502, 2503, 2504, 2505, 2506, 2507, 2508, 2509, 2510, 2511, 2512, 2513, 2514, 2515, 2516,
        2517, 2518, 2519, ..., 2979, 2980, 2981, 2982, 2983, 2984, 2985, 2986, 2987, 2988, 2989, 2990, 2991,
        2992, 2993, 2994, 2995, 2996, 2997, 2998]))

time: 1.66 ms


In [112]:
allDone()

time: 1.47 ms


# 6. Runs the training
Run it the training! Save the weights! 
- Make the predictions


In [113]:
max_log_y = np.max(yl)
y_range = (0, max_log_y*1.2)

time: 912 µs


In [114]:
max_log_y,y_range

(1.0, (0, 1.2))

time: 1.47 ms


In [115]:
type(cat_vars),cat_vars[:5]

(list,
 ['ps_ind_02_cat',
  'ps_ind_04_cat',
  'ps_ind_05_cat',
  'ps_ind_06_bin',
  'ps_ind_07_bin'])

time: 1.7 ms


In [117]:
md = ColumnarModelData.from_data_frame(path, val_idx, df, yl, cat_flds=cat_vars, bs=128)

time: 8.83 ms


In [118]:
#cat_sz = {c: len(joined_samp[c].cat.categories)+1 for c in cat_vars}
cat_sz = {c: len(joined[c].cat.categories)+1 for c in cat_vars}
emb_szs = [(c, min(50, (c+1)//2)) for _,c in cat_sz.items()]

time: 2.67 ms


In [119]:
joined.ps_calc_15_bin.unique()

[0, 1]
Categories (2, int64): [0 < 1]

time: 2.26 ms


In [120]:
joined.dtypes

ps_ind_02_cat     category
ps_ind_04_cat     category
ps_ind_05_cat     category
ps_ind_06_bin     category
ps_ind_07_bin     category
ps_ind_08_bin     category
ps_ind_09_bin     category
ps_ind_10_bin     category
ps_ind_11_bin     category
ps_ind_12_bin     category
ps_ind_13_bin     category
ps_ind_16_bin     category
ps_ind_17_bin     category
ps_ind_18_bin     category
ps_car_01_cat     category
ps_car_02_cat     category
ps_car_03_cat     category
ps_car_04_cat     category
ps_car_05_cat     category
ps_car_06_cat     category
ps_car_07_cat     category
ps_car_08_cat     category
ps_car_09_cat     category
ps_car_10_cat     category
ps_car_11_cat     category
ps_calc_15_bin    category
ps_calc_16_bin    category
ps_calc_17_bin    category
ps_calc_18_bin    category
ps_calc_19_bin    category
ps_calc_20_bin    category
ps_car_11          float32
ps_car_12          float32
ps_car_13          float32
ps_ind_14          float32
ps_ind_15          float32
ps_ind_01          float32
p

time: 2.84 ms


In [121]:
m = md.get_learner(emb_szs, len(df.columns)-len(cat_vars),
                   0.04, 1, [1000,500], [0.001,0.01], y_range=None)#y_range)
lr = 1e-3

time: 3min 39s


In [122]:
m.lr_find()

HBox(children=(IntProgress(value=0, description='Epoch', max=1), HTML(value='')))

 45%|████▌     | 9/20 [00:03<00:03,  2.78it/s, loss=0.601]
time: 3.46 s                                              


In [125]:
m.sched.plot(100)

AttributeError: 'LossRecorder' object has no attribute 'plot'

time: 4.94 ms


In [126]:
m.fit(lr, 10, metrics=[exp_rmspe])

HBox(children=(IntProgress(value=0, description='Epoch', max=10), HTML(value='')))

[ 0.       0.04646  0.03428  0.12326]                       
[ 1.       0.03846  0.0352   0.13845]                       
[ 2.       0.03434  0.03558  0.13808]                       
[ 3.       0.03074  0.03807  0.13741]                       
[ 4.       0.0272   0.04102  0.16277]                       
[ 5.       0.02374  0.04033  0.15138]                       
[ 6.       0.02046  0.04354  0.16712]                       
[ 7.       0.0172   0.04378  0.17179]                       
[ 8.       0.01452  0.04135  0.16183]                       
[ 9.       0.01188  0.0423   0.16036]                       

time: 18.8 s


# 7. Analyze Results
Are they what are expected? 
- Graph the results
- What are the most important features
- What do tough predictions look like? Easy predictions?

# 8. Submit!
- Get it put into a submitable template
- Save results